# -*- coding: utf-8 -*-
"""scatter2D.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MFZ1JwkxUbxApJbuz9EYrUNDMPF5z2a6
"""

# import required packages 
from bokeh.models import Slider, ColumnDataSource, Paragraph
from bokeh.io import curdoc
from bokeh.layouts import row 
from bokeh.plotting import figure 
from bokeh.transform import factor_cmap, factor_mark
from bokeh.layouts import gridplot

#create data for the plot 

from numpy.random import random

initial_points = 500 

data_points = ColumnDataSource(data = {'x' : random(initial_points), 'y' : random(initial_points)})
# source = ColumnDataSource(df) for pandas

#create the actual plot

plot = figure(title = 'Scatter Plot with Slider')

plot.diamond(x = 'x', y = 'y', source= data_points, color = 'red')

#create the slider widget 

slider_widget = Slider(start=0, end=10000, step=10, value=initial_points, title='Slide right to increase number of points')

#define call back function

def callback(attr, old, new):
  points = slider_widget.value
  data_points.data = ({'x' : random(points), 'y' : random(points)})
slider_widget.on_change('value', callback)

#create the actual secon plot

plot2 = figure(title = 'Scatter Plot with Slider')

plot2.diamond(x = 'x', y = 'y', source= data_points, color = 'red' )

# Create text paragraph
welcome_message = 'Hello and welcome to Andrea and Lars magnificant data shwo'
welcome_banner = Paragraph(text=welcome_message, width=200, height=100)

conclusion_message = 'Therefore the conclusion must be that the most amount of tested people is the most favourble strategy, both in terms of death pr capita and economic gains.'
conclusion_banner = Paragraph(text=conclusion_message, width=400, height=200)

#create layout for application


layout = gridplot([[welcome_banner], 
                   [slider_widget, plot, plot2], 
                   [conclusion_banner]], plot_width=250, plot_height=250)

#add layout to application


curdoc().add_root(layout)